<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="viratsardana" >

    <title>DezyreBot</title>

    <!-- Bootstrap Core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    
     <script src="http://code.jquery.com/jquery-2.1.4.js"></script>
   

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
    
    
    <script type="text/javascript" >
		  
		  
    
    	  var socket =io.connect("http://localhost:3000/");
		  
		  var current_user_connected=parseInt(<?php echo $this->message; ?>)
		  
		  // alert(current_user_connected);

          var questions_displayed=0;

          var questions=[];

          var questions_id=[];

          var general_questions=[];

          var general_questions_id=[];

          var general_questions_displayed=0;

          var flag=0;
		  
		  socket.emit('user_id',current_user_connected);

    	 
    	 function send_message(){

        if(!flag){
    	 	 
    	 	 user_message=document.getElementById("user-message");
    	 	 
    	 	 user_message_value=user_message.value;    	 	 
    	 	     	 	 
			 user_message.value="";    	 	 
    	 	 
		 	 //alert(user_message_value);
		 	 
		 	 
		 	 //will have to edit this value with some identifier for ease at back end
             if(questions_displayed<=questions.length){
		 	  socket.emit('chat message',user_message_value+"-"+questions_id[questions_displayed-1]);
              if(questions_displayed==questions.length) questions_displayed++;
            }

             //append user answer to chat area

             $("#chat-area").append("<div class='media' style='margin-left:0px'>" +
                        "<a class='media-left' href='#''>" +
                            "<img class='media-object' src='/botimages/default.png' height='40px'></img>"+
                        "</a>" +
                        "<div class='media-body'><b>Username</b><br>"+user_message_value+"</div></div>");

             $("#chat-area").scrollTop($("#chat-area")[0].scrollHeight);


             

             //display next question in chat area now
             if(questions_displayed<=questions.length-1){
              display_question(questions_displayed);
             }

             else{
                
                if(general_questions.length>0 && general_questions_displayed <= general_questions.length-1)
                 display_general_questions(general_questions_displayed);

                flag=1;
                 
             }		

        }

       else if(flag==1){

            send_general_question();

        } 	     	 	     	 
    	 
    }
    	 
    	 
    	 function get_message(){
    	 	 
    	 	 //alert("hello get_message");	
    	 	 
    	 	 //also need some way to send user id from this page
    	 	 
    	 	 socket.emit('body loaded','loaded');

             socket.on('question',function(ques){

                //alert(ques);

                //questions.push(ques);

                for(var i=0;i<ques.length;i++){
                    var splt=ques[i].split("-");
                    questions.push(splt[0]);
                    questions_id.push(splt[1]);
                }

                if(questions.length>0){
                //alert(questions.length);
                display_question(0);}

                //this code is waste general questions is not ready at the moment 
                
               /* else{

                    if(general_questions.length>0){
                        display_general_question(0);
                        flag=1;
                    }

                }*/


             });

             //-------------------------------------------------------------------------------------//
             
             
             
             socket.on('photo-upload',function(msg){
			 
				

				$("#chat-area").append("<div class='media' style='margin-left:0px'>" +
                        "<a class='media-left' href='#''>" +
                            "<img class='media-object' src='/botimages/hubot.png' height='40px'></img>"+
                        "</a>" +
                        "<div class='media-body'><b>DezyreBot</b><br>"+msg.split("-")[0]+"</div></div><br><form id='uploadform' enctype='multipart/form-data' method='POST'><input type='file' name='f'><br><input type='submit' id='upload-image-button' value='Upload Picture' class='btn btn-info'></form>"); 			 
			    
			    document.getElementById("uploadform").addEventListener('submit',function(e){
			 
			    e.preventDefault();
			  
				var fd=new FormData(this);
			
				$.ajax({
				 type:'POST',
				 url:'/user/pictureuploadbot',
				 data:fd,
				 cache:false,
				 contentType:false,
				 processData:false,
				 success:function(data){
						//alert('success');
				 }
				
				
				});
			 
			    });
				
			    
			 
			 });


			 socket.on('general-question',function(msg){

				 //alert(msg);

				 var splt=msg.split('-');

				 general_questions.push(splt[0]);

				 general_questions_id.push(splt[1]);

				 //alert('general questions length '+general_questions.length);

				 if(questions.length==0 || questions_displayed > questions.length-1) flag=1;

				 if(questions.length==0 || questions_displayed > questions.length-1)
					 if(general_questions.length > 0 && general_questions_displayed<=general_questions.length-1)
						 display_general_questions(general_questions_displayed);				 


			});






             //-------------------------------------------------------------------------------------//			 
    	 
    	 }

    	 var wait_for_response=0;

    	 function display_general_questions(question_number){

        	 //alert('hello');
        	 if(wait_for_response) return;

    		 $("#chat-area").append("<div class='media' style='margin-left:0px'>" +
                     "<a class='media-left' href='#''>" +
                         "<img class='media-object' src='/botimages/hubot.png' height='40px'></img>"+
                     "</a>" +
                     "<div class='media-body'><b>DezyreBot</b><br>"+general_questions[question_number]+"</div></div>");

             $("#chat-area").scrollTop($("#chat-area")[0].scrollHeight);



         wait_for_response=1-wait_for_response;

         general_questions_displayed++;

        	 


         }

         function send_general_question(){

             //alert('you are here');

             wait_for_response=1-wait_for_response;

             
			 user_message=document.getElementById("user-message");
    	 	 
    	 	 user_message_value=user_message.value;

    	 	//alert(user_message_value+"-"+general_questions_id[general_questions_displayed-1]);    	 	 
    	 	     	 	 
			 user_message.value="";

			 if(general_questions_displayed<=general_questions.length){
				  //alert(general_questions_displayed);
	   		 	  socket.emit('general_hackathon',user_message_value+"-"+general_questions_id[general_questions_displayed-1]);
	   		 	//alert(general_questions.length+"-"+general_questions_displayed);
	   		 	  if(general_questions.length==general_questions_displayed){ general_questions_displayed++; } 
	               }

			 $("#chat-area").append("<div class='media' style='margin-left:0px'>" +
                     "<a class='media-left' href='#''>" +
                         "<img class='media-object' src='/botimages/default.png' height='40px'></img>"+
                     "</a>" +
                     "<div class='media-body'><b>Username</b><br>"+user_message_value+"</div></div>");

          $("#chat-area").scrollTop($("#chat-area")[0].scrollHeight);


          
          

          if(general_questions_displayed < general_questions.length)
              display_general_questions(general_questions_displayed);
               

             


         }

         
				 

         function display_question(question_number){

            //code for appending to the div where chat is displayed goes here
            //alert(questions[question_number]);

            
                $("#chat-area").append("<div class='media' style='margin-left:0px'>" +
                        "<a class='media-left' href='#''>" +
                            "<img class='media-object' src='/botimages/hubot.png' height='40px'></img>"+
                        "</a>" +
                        "<div class='media-body'><b>DezyreBot</b><br>"+questions[question_number]+"</div></div>");

                $("#chat-area").scrollTop($("#chat-area")[0].scrollHeight);


            questions_displayed++;
         }
    	 
    	 function search(ele){
    	 
    	 	 //alert(event.keyCode);
    	 
    	 	 if(event.keyCode==13){
    	 	 	 //alert("hello");
    	 	 	 send_message();    	 	 
    	 	 }    	 
    	 
    	 }
    	 
    	 

	 </script>
	 
	 <style>

     html,body{
        height: 100%;
        margin: 0;
     }


	 #wrapper {
    padding-left: 0;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
}

#wrapper.toggled {
    padding-left: 250px;
}

#sidebar-wrapper {
    z-index: 1000;
    position: fixed;
    left: 250px;
    width: 50%;
    height: 100%;
    margin-left: -250px;
    overflow-y: auto;
    background: #000;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
}

#wrapper.toggled #sidebar-wrapper {
    width: 250px;
}

#page-content-wrapper {
    width: 100%;
    position: absolute;
    padding: 15px;
}

#wrapper.toggled #page-content-wrapper {
    position: absolute;
    margin-right: -250px;
}

/* Sidebar Styles */

.sidebar-nav {
    position: absolute;
    top: 0;
    width: 250px;
    margin: 0;
    padding: 0;
    list-style: none;
}

.sidebar-nav li {
    text-indent: 20px;
    line-height: 40px;
}

.sidebar-nav li a {
    display: block;
    text-decoration: none;
    color: #999999;
}

.sidebar-nav li a:hover {
    text-decoration: none;
    color: #fff;
    background: rgba(255,255,255,0.2);
}

.sidebar-nav li a:active,
.sidebar-nav li a:focus {
    text-decoration: none;
}

.sidebar-nav > .sidebar-brand {
    height: 65px;
    font-size: 18px;
    line-height: 60px;
}

.sidebar-nav > .sidebar-brand a {
    color: #999999;
}

.sidebar-nav > .sidebar-brand a:hover {
    color: #fff;
    background: none;
}

@media(min-width:768px) {
    #wrapper {
        padding-left: 250px;
    }

    #wrapper.toggled {
        padding-left: 0;
    }

    #sidebar-wrapper {
        width: 250px;
    }

    #wrapper.toggled #sidebar-wrapper {
        width: 0;
    }

    #page-content-wrapper {
        padding: 20px;
        position: relative;
    }

    #wrapper.toggled #page-content-wrapper {
        position: relative;
        margin-right: 0;
    }
}
	 </style>

</head>

<body onload="get_message()">

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
        		<ul class="sidebar-nav">
            	<li class="sidebar-brand">
                    <a href="#">
                     <span class="glyphicon glyphicon-lamp"></span>&nbsp;Dezyre Bot
                    </a>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-comment"></span>&nbsp;&nbsp;Direct Message</a>
                </li>
                
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
            	 <div class="row" id="header">
            	 	 <div class="col-lg-12">
            	 	 	 <h4 style="display:inline"><font color="grey">@</font>dezyrebot</h4>
            	 	 	 <img src="/botimages/online.png" height="10px"></img>
            	 	 	 <br><br>
            	 	 </div>            	             	 
            	 </div>
                 
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Hi, This is Dezyre Bot</h1>
                </div>
                <div class="row" style="height:80px; positon:fixed; padding:15px;">
                	 <div class="col-lg-1"><img src="/botimages/hubot.png" height="40px" style="position:relative; left:30px"></div>
                	 <div class="col-lg-6">
                        <p style="font-size:20px"><b>This is the beginning of your chat history with Dezyrebot. Dezyrebot
                        is pretty dumb, but it tries to be helpful</b></p>
                        <hr></hr>
                    </div>
                    </div>
                </div>
                
                <div class="row" id="chat-area" style="padding-bottom:95px; padding:15px; overflow:auto; height:320px;">
                	             
                </div>

                

                
                <div class="row" style="bottom:0; position:fixed; height:80px;">
                	 <div class="col-lg-11">
                	 	 <div class="input-group">
                                    <input type="text" id="user-message" class="form-control" placeholder="Enter Message" onkeydown="search(this)"/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-info" type="button" onclick="send_message()">SEND</button>
                                    </span>
                                </div>
                	 </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    

</body>

</html>
